workspace:
  base: /go
  path: src/github.com/heetch/rules-engine

pipeline:
  build:
    image: golang:1.10-alpine
    commands:
      - echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
      - apk --update add git dep make
      - dep ensure
      - make test
    when:
      event: [ push, tag ]

  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/heetch/rules-engine
    secrets: [ plugin_username, plugin_password ]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      event: tag

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379:2379"
    command: /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
