workspace:
  base: /go
  path: src/github.com/heetch/rules-engine

pipeline:
  build:
    image: golang:1.9-alpine
    commands:
      - apk --update add git glide
      - glide --quiet install
      - go test -v ./...
    when:
      event: push

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379:2379"
    command: /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
