sudo: required

language: go

services:
  - docker

before_install:
  - docker run -d -p 2379:2379 quay.io/coreos/etcd /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379

go:
  - '1.11.x'
  - '1.12.x'
  - tip

script:
  - GO111MODULE=on go test -v -race -cover -timeout=1m ./...

deploy:
  provider: script
  skip_cleanup: true
  script: .ci/docker.sh
  on:
    tags: true
    go: '1.12.x'
