version: "3"

services:
  etcd:
    image: "quay.io/coreos/etcd:latest"
    ports:
      - "2379:2379"
    command: /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
